# Check https://circleci.com/docs/2.0/ for more details
# for config.yml syntax see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1

jobs:
  linux-test:
    docker:
      - image: circleci/node:10.15.0-browsers

    working_directory: ~/repo
    parallelism: 2
    steps:
      - checkout
      # Download and cache dependencies for the app and for tests
      - restore_cache:
          keys:
            - dependencies-{{ arch }}-{{ .Branch }}-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - dependencies-{{ arch }}-{{ .Branch }}-

      - run: npm install

      - save_cache:
          paths:
            # local NPM modules
            - node_modules
            # all NPM modules
            - ~/.npm
            # Cypress binary (or yarn dependencies) on Linux
            - ~/.cache
          key: dependencies-{{ arch }}-{{ .Branch }}-{{ checksum "package.json" }}

      - run: npm run serve-and-test:ci

workflows:
  version: 2
  tests:
    jobs:
      - linux-test
